pipeline {
    agent any
    
    triggers {
        githubPush()
    }
    
    stages {
        stage('Push'){
            steps {
                echo 'Success to check push'
            }
        }
    }
    
}