pipeline {
    agent any

    // 불필요한 코드 삭제
    // triggers {
    //     githubPush()
    // }

    stages {
        stage('for the PR') {
            when {
                branch 'PR-*'
            }
            steps {
                echo '*** this only runs for the PRs ***'
            }
        }

        stage('github_clone') {
            steps {
                git branch: 'feature/10-chaeeun-han', credentialsId: 'CUBIXJenkinsTest', url: 'https://github.com/GDSC-CUBIX/EZPZ-Infra-Study.git'
            }
        }

        stage('secrets.yml download') {
            steps {
                withCredentials([file(credentialsId: 'test-secrets', variable: 'dbConfigFile')]) {
                    script {
                        sh 'cp $dbConfigFile dev/chaeeun-han/ext-search-batch/src/test/resources/application-secrets.yml'
                        sh 'cp $dbConfigFile dev/chaeeun-han/ext-search-batch/src/main/resources/application-secrets.yml'
                    }
                }
            }
        }

        stage('build') {
            steps {
                dir('dev/chaeeun-han/ext-search-batch'){
                    sh """
                    chmod +x ./gradlew
                    ./gradlew clean build -x test
                    """
                }
            }
        }

    post {
        success {
            echo "*** status: SUCCESS"
        }
        failure {
            echo "*** status: FAILURE"
        }
    }
}