spring:
  datasource:
    url: 
    driver-class-name : 
    username: 
    password: 
  mvc:
    servlet:
      load-on-startup: 1
  jpa:
    database : mysql
    database-platform : org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show_sql: true
      format_sql: true
      use_sql_comments: true
  profiles:
    include :
      - secrets
      
server:
  port: 8081


naver :
  client:
    iD: 
    secret: 
  base:
    url: https://openapi.naver.com/v1/search/news.json
    path: /v1/search/news.json
